# .github/workflows/run.yml
name: Telethon Admin Finder

on:
  workflow_dispatch:

jobs:
  find-admins:
    environment: production
    runs-on: ubuntu-latest
    env:
      API_ID: ${{ secrets.API_ID }}
      API_HASH: ${{ secrets.API_HASH }}
      TELEGRAM_SESSION_BASE64: ${{ secrets.TELEGRAM_SESSION_BASE64 }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Restore Telethon session file
        run: |
          echo "${{ secrets.TELEGRAM_SESSION_BASE64 }}" | base64 --decode > session_name.session.gz
          gunzip session_name.session.gz
      - name: Run Telethon script
        run: python find_admins.py