name: Telethon Admin Finder

# Запуск вручную
on:
  workflow_dispatch:

jobs:
  find-admins:
    runs-on: ubuntu-latest
    env:
      # Секреты, добавленные в Settings → Secrets → Actions
      API_ID:   ${{ secrets.API_ID }}
      API_HASH: ${{ secrets.API_HASH }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Telethon script
        # Здесь можно добавить любые опции: --output, --verbose и т.п.
        run: python find_admins.py --output admins_list.csv

      - name: Upload admins list
        uses: actions/upload-artifact@v3
        with:
          name: admins-list
          path: admins_list.csv
