# .github/workflows/run.yml
name: Telethon Admin Finder

on:
  workflow_dispatch:          # ручной запуск

jobs:
  find-admins:
    runs-on: ubuntu-latest
    env:
      API_ID:   ${{ secrets.API_ID }}
      API_HASH: ${{ secrets.API_HASH }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Telethon script
        # записываем вывод в временную папку раннера, а не в корень репо
        run: |
          OUT="$RUNNER_TEMP/admins_list.csv"
          python find_admins.py --output "$OUT"
          echo "OUT=$OUT" >> $GITHUB_ENV
        # сохраним путь в переменной, чтобы передать дальше
        id: run

      - name: Upload admins list artifact
        uses: actions/upload-artifact@v3
        with:
          name: admins-list
          path: ${{ ENV.OUT }}
          retention-days: 1
